### ISSUE TITLE
Website hard to read for eye handicaped people

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd.com#145]
Hi,

I had opened a ticket in the wrong repo. I repeat it here:

Original ticket was here:

https://github.com/vstakhov/rspamd/issues/953#issuecomment-247342672

-------------------------------

I am pretty sure, this is not the optimal place for my question, but I don't know a better place.

My eyes are bad in two ways: One is I am red/green blind, as are 11% of all men. Reading the code snippet boxes is nearly impossible.

At the other side I also have MAcula Degeneration and I need to switch colors to inverse. This makes the code boxes as well unreadable. So for people like me, the documentation for this project is in some way unreachable.

What I ask is, if it was possible to use a different collor scheme. Ideally, the code boxes would also be based on a white background.

I hope there is some chance that this could be changed :-) I really love this project and I would very much love to dive deeper into it, if I could read the docs ;-)

Best wishes

Christian

**Comment by vstakhov** [comment]
I do not completely understand this issue. Can you see green text on black background? Maybe there are some guides to follow when choosing the colors in this case?

**Comment by croessner** [comment]
I send you a screenshot via email ;-) Wait a moment

**Comment by croessner** [comment]
![img_3924](https://cloud.githubusercontent.com/assets/2562594/18584348/75255514-7c10-11e6-8539-7244c401b0be.JPG)
![img_3923](https://cloud.githubusercontent.com/assets/2562594/18584349/755a8aae-7c10-11e6-86fa-9be1e8d50494.JPG)

This is, what colors become when inverting the screen.

**Comment by croessner** [comment]
Sorry, for some reason the browser has turned the pictures in wrong direction :-( But you still get the idea

**Comment by croessner** [comment]
So if you use a white background, all is perfect. Here is an example from my side:

https://www.roessner-network-solutions.com/backup-von-kvm-gaesten-im-laufenden-betrieb/

It is perfectly readble on normal and inverted screen

**Comment by vstakhov** [comment]
I have changed the color scheme. Does it look readable now?

**Comment by croessner** [comment]
Yessss!!! Thank you so very, very much. You rock. Now that is absolutely perfect for reading :-)
