### ISSUE TITLE
Document how to expose webui on nginx subdir

### ISSUE THREAD

**Issue by julienmalik** [vstakhov/rspamd.com#35]
Currently the quickstart documents how to expose the webui via nginx, but only at the root of a domain.

The following configuration works-for-me to expose the webui under a subdir.

```
location /rspamd/ {
  proxy_pass       http://localhost:11334/;

  proxy_set_header Host      $host;
  proxy_set_header X-Real-IP $remote_addr;
}
```

The important part is to not miss the trailing '/' at the end of location directive.
For the rest, proxy_pass does the job (also requires the trailing '/' there), and no rewrite is necessary.

It would be nice to have it documented somewhere.

**Comment by julienmalik** [comment]
This is working for nginx 1.6

**Comment by quicktrick** [comment]
Hello!

Can I make the `proxy_pass` via a UNIX socket?  And how to configure the UNIX socket in the proxy worker?

P.S. Всеволод, пожалуйста, подскажите новичку, очень сложно практически с нуля разобраться в конфигурировании всех компонентов, несмотря на столь развитую документацию. Примеров маловато, честно. И в Интернете такого нет, обыскался просто. У меня просто всё на Unix-сокетах работает, и плодить зоопарк не хочется. Заранее спасибо!  Александр
